name       : kdebugsettings
version    : 23.04.1
release    : 51
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.1/src/kdebugsettings-23.04.1.tar.xz : 19c681cecef4caecbd8d9f56526015e72dc073ca6b66553639287a7465fef8a2
homepage   : https://kde.org/applications/development/org.kde.kdebugsettings
license    : LGPL-2.0-or-later
component  : desktop.kde
summary    : Application to enable/disable qCDebug
description: |
    An application to enable/disable qCDebug.
builddeps  :
    - kcompletion-devel
    - kconfig-devel
    - kcoreaddons-devel
    - kdbusaddons-devel
    - ki18n-devel
    - kitemviews-devel
    - kxmlgui-devel
    - kwidgetsaddons-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
