name       : kdebugsettings
version    : 21.04.3
release    : 36
source     :
    - https://cdn.download.kde.org/stable/release-service/21.04.3/src/kdebugsettings-21.04.3.tar.xz : c1d7259a293976a609436724ff26945a0e0fb166af037db79e345a2f3c77fe51
homepage   : https://kde.org/applications/development/org.kde.kdebugsettings
license    : LGPL-2.0-or-later
component  : desktop.kde
summary    : Application to enable/disable qCDebug
description: |
    An application to enable/disable qCDebug.
builddeps  :
    - kcompletion-devel
    - kconfig-devel
    - kcoreaddons-devel
    - kdbusaddons-devel
    - ki18n-devel
    - kitemviews-devel
    - kwidgetsaddons-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
