name       : kdebugsettings
version    : 21.04.2
release    : 35
source     :
    - https://cdn.download.kde.org/stable/release-service/21.04.2/src/kdebugsettings-21.04.2.tar.xz : a2b341875ea97f1f8bb9c98bd7ba10971180c6fd10fa1142d8f38d9b7ff764c6
homepage   : https://kde.org/applications/development/org.kde.kdebugsettings
license    : LGPL-2.0-or-later
component  : desktop.kde
summary    : Application to enable/disable qCDebug
description: |
    An application to enable/disable qCDebug.
builddeps  :
    - kcompletion-devel
    - kconfig-devel
    - kcoreaddons-devel
    - kdbusaddons-devel
    - ki18n-devel
    - kitemviews-devel
    - kwidgetsaddons-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
