name       : kdebugsettings
version    : 20.04.1
release    : 21
source     :
    - https://cdn.download.kde.org/stable/release-service/20.04.1/src/kdebugsettings-20.04.1.tar.xz : 5ef5e45c37c9a2922d201f7053b9ed27cf9675c575cb2bb607dda13c86723dd8
homepage   : https://kde.org/applications/development/org.kde.kdebugsettings
license    : LGPL-2.0-or-later
component  : desktop.kde
summary    : Application to enable/disable qCDebug
description: |
    An application to enable/disable qCDebug.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcompletion-devel
    - kconfig-devel
    - kcoreaddons-devel
    - kdbusaddons-devel
    - ki18n-devel
    - kitemviews-devel
    - kwidgetsaddons-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
