name       : kdebugsettings
version    : 20.08.2
release    : 26
source     :
    - https://cdn.download.kde.org/stable/release-service/20.08.2/src/kdebugsettings-20.08.2.tar.xz : 78502b1a52f9f81ff848e5b210b37a3a74da7c0032de2513f23c1d25cf801283
homepage   : https://kde.org/applications/development/org.kde.kdebugsettings
license    : LGPL-2.0-or-later
component  : desktop.kde
summary    : Application to enable/disable qCDebug
description: |
    An application to enable/disable qCDebug.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcompletion-devel
    - kconfig-devel
    - kcoreaddons-devel
    - kdbusaddons-devel
    - ki18n-devel
    - kitemviews-devel
    - kwidgetsaddons-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
