name       : kdebugsettings
version    : 18.12.0
release    : 4
source     :
    - https://cdn.download.kde.org/stable/applications/18.12.0/src/kdebugsettings-18.12.0.tar.xz : 47b479b2cf5246ef5a29257600b6c841fbcd6180bc6c2ca9896dab557a60b9bd
license    : LGPL-2.0-or-later
component  : desktop.kde
summary    : Application to enable/disable qCDebug
description: |
    An application to enable/disable qCDebug.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcompletion-devel
    - kconfig-devel
    - kcoreaddons-devel
    - kdbusaddons-devel
    - ki18n-devel
    - kitemviews-devel
    - kwidgetsaddons-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
