name       : kdebugsettings
version    : 19.08.2
release    : 14
source     :
    - https://cdn.download.kde.org/stable/applications/19.08.2/src/kdebugsettings-19.08.2.tar.xz : 2823e53da647dec2bd780a3029c6b093917faad3db973147ef74eb8f1c1733df
license    : LGPL-2.0-or-later
component  : desktop.kde
summary    : Application to enable/disable qCDebug
description: |
    An application to enable/disable qCDebug.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcompletion-devel
    - kconfig-devel
    - kcoreaddons-devel
    - kdbusaddons-devel
    - ki18n-devel
    - kitemviews-devel
    - kwidgetsaddons-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
