name       : kdebugsettings
version    : 21.08.3
release    : 40
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.3/src/kdebugsettings-21.08.3.tar.xz : 84d2cd17d5d9eb9805cab7c7d108c13e1d7d5e81203ce77fa730bc0ef68b87b4
homepage   : https://kde.org/applications/development/org.kde.kdebugsettings
license    : LGPL-2.0-or-later
component  : desktop.kde
summary    : Application to enable/disable qCDebug
description: |
    An application to enable/disable qCDebug.
builddeps  :
    - kcompletion-devel
    - kconfig-devel
    - kcoreaddons-devel
    - kdbusaddons-devel
    - ki18n-devel
    - kitemviews-devel
    - kwidgetsaddons-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
