name       : kdebugsettings
version    : 18.12.2
release    : 6
source     :
    - https://cdn.download.kde.org/stable/applications/18.12.2/src/kdebugsettings-18.12.2.tar.xz : f40b565148ef123d9f0ccac24228434081d0a3caa14d7c044f08a9471aa08c7b
license    : LGPL-2.0-or-later
component  : desktop.kde
summary    : Application to enable/disable qCDebug
description: |
    An application to enable/disable qCDebug.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcompletion-devel
    - kconfig-devel
    - kcoreaddons-devel
    - kdbusaddons-devel
    - ki18n-devel
    - kitemviews-devel
    - kwidgetsaddons-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
