name       : kdebugsettings
version    : 20.12.2
release    : 31
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.2/src/kdebugsettings-20.12.2.tar.xz : 96ed75eaed1265931859007cbd761351c5b7077435304695746c3d3a99deedb7
homepage   : https://kde.org/applications/development/org.kde.kdebugsettings
license    : LGPL-2.0-or-later
component  : desktop.kde
summary    : Application to enable/disable qCDebug
description: |
    An application to enable/disable qCDebug.
builddeps  :
    - kcompletion-devel
    - kconfig-devel
    - kcoreaddons-devel
    - kdbusaddons-devel
    - ki18n-devel
    - kitemviews-devel
    - kwidgetsaddons-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
