name       : kdebugsettings
version    : 18.08.2
release    : 2
source     :
    - https://cdn.download.kde.org/stable/applications/18.08.2/src/kdebugsettings-18.08.2.tar.xz : 18d2a718473320065d405fdbe2d66f549ef700d848c86d3fc65aa7357c3fe3e8
license    : LGPL-2.0-or-later
component  : desktop.kde
summary    : Application to enable/disable qCDebug
description: |
    An application to enable/disable qCDebug.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcompletion-devel
    - kconfig-devel
    - kcoreaddons-devel
    - kdbusaddons-devel
    - ki18n-devel
    - kitemviews-devel
    - kwidgetsaddons-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
