name       : kdebugsettings
version    : 23.04.0
release    : 50
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.0/src/kdebugsettings-23.04.0.tar.xz : fe151d8be7827b40a0ef81eeaab9ec1fc4244aaae90074b3b8098450a9c4cc6b
homepage   : https://kde.org/applications/development/org.kde.kdebugsettings
license    : LGPL-2.0-or-later
component  : desktop.kde
summary    : Application to enable/disable qCDebug
description: |
    An application to enable/disable qCDebug.
builddeps  :
    - kcompletion-devel
    - kconfig-devel
    - kcoreaddons-devel
    - kdbusaddons-devel
    - ki18n-devel
    - kitemviews-devel
    - kxmlgui-devel
    - kwidgetsaddons-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
