name       : kdebugsettings
version    : 18.08.3
release    : 3
source     :
    - https://cdn.download.kde.org/stable/applications/18.08.3/src/kdebugsettings-18.08.3.tar.xz : f990a27a69f0a5943b022e0f8d7b329cdcac037cdab7265534df41abc7446be8
license    : LGPL-2.0-or-later
component  : desktop.kde
summary    : Application to enable/disable qCDebug
description: |
    An application to enable/disable qCDebug.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcompletion-devel
    - kconfig-devel
    - kcoreaddons-devel
    - kdbusaddons-devel
    - ki18n-devel
    - kitemviews-devel
    - kwidgetsaddons-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
